<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SRK" ignored="0" name="Test" tests="6" failures="3" timestamp="12 Nov 2020 09:49:32 GMT" time="11.777" errors="0">
  <testcase name="validateCreateCustWithValidKey" time="4.022" classname="com.w2a.testcases.DataUsingHashtable"/>
  <testcase name="validateCreateCustWithValidKey" time="1.647" classname="com.w2a.testcases.DataUsingHashtable"/>
  <testcase name="validateCreateCustWithValidKey" time="1.609" classname="com.w2a.testcases.DataUsingHashtable"/>
  <testcase name="validateCreateCustWithInValidKey" time="1.336" classname="com.w2a.testcases.DataUsingHashtable">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.w2a.testcases.DataUsingHashtable.validateCreateCustWithInValidKey(DataUsingHashtable.java:47)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustWithInValidKey -->
  <testcase name="validateCreateCustWithInValidKey" time="1.308" classname="com.w2a.testcases.DataUsingHashtable">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.w2a.testcases.DataUsingHashtable.validateCreateCustWithInValidKey(DataUsingHashtable.java:47)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustWithInValidKey -->
  <testcase name="validateCreateCustWithInValidKey" time="1.618" classname="com.w2a.testcases.DataUsingHashtable">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.w2a.testcases.DataUsingHashtable.validateCreateCustWithInValidKey(DataUsingHashtable.java:47)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustWithInValidKey -->
</testsuite> <!-- Test -->
